# Conda environment for building the MELODIES-MONET docs
name: melodies-monet-docs
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.11
  - esmpy
  - pip
  - pip:
    # Core MM Dependencies (with requested branches)
    - "monet @ git+https://github.com/noaa-oar-arl/monet.git@develop"
    - "monetio @ git+https://github.com/bbakernoaa/monetio.git@develop"
    - "monet-stats @ git+https://github.com/bbakernoaa/monet-stats.git@main"
    - "monet-plots @ git+https://github.com/bbakernoaa/monet-plots.git@main"
    # Other core dependencies
    - networkx
    - prefect
    - pyyaml
    - prefect-dask
    - dask-jobqueue
    # Docs tools
    - ipykernel
    - jupyterlab=4.*
    - jupytext
    - "myst-nb>=0.14"
    - nbclient
    - "sphinx=7.*"
    - sphinx-autobuild
    - sphinx-click
    - sphinx-design
    - sphinx_rtd_theme
    - sphinx-togglebutton
    # melodies_monet itself
    - '-e ../'
